version: '3'
services:
  broker:
    
    image: alijabbar/brokerimge
    container_name: broker
    
      
    ports:
      - 8000:8000

  user:
   image: "alijabbar/userservice"
    
   ports:
    - 8081:8081
   depends_on:
    - mongodb

  mongodb:
   image: mongo
   container_name: mongodb
   ports:  
    - 27017:27017
   volumes:
    - /home/ali/E/Go/toDo/backend-service/mongodb-data:/data/db
  auth:
   
   image: alijabbar/auth-service
   

   ports:
    - 8082:8082
   depends_on:
    - mongodb
  task:
  
   image: "alijabbar/task-service"
   ports:
    - 8083:8083
   depends_on:
    - mongodb
  frontend:
   
   image: alijabbar/frontimge:latest
   
   ports:
    - 80:80
   
    

      
